include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_typing_uninitialized_variables
    - prefer_final_fields
    - prefer_const_declarations
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_function_literals_in_foreach_calls
    - prefer_single_quotes
    - require_trailing_commas
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore